### ISSUE TITLE
Label rendering issue

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-carto-libs#1]
I see that you are working on labels rendering https://github.com/CartoDB/mobile-carto-libs/commit/82e8ee595fa30cd724ea86d07a76d89f5e915407.

Would that affect that issue https://github.com/CartoDB/mobile-sdk/issues/176 ?
It's a pretty annoying one as you end up not seeing Big cities names

**Comment by mtehver** [comment]
@farfromrefug I tried to reproduce this with SDK 4.2.0, but this seemed to work fine. I do not remember exactly fixing this, but there has been major changes in label rendering vs 4.1.x releases.

**Comment by farfromrefug** [comment]
@mtehver just tested right now on 4.2.0 (with your latest commits) and i am sorry to say the issue is still there. You will in the gif that the first times it works, Geneva remains the one visible. But the last time Geneva disappears. Very easy to reproduce
![a3y17ltePQ2A 190405 003mguillon04272019200821](https://user-images.githubusercontent.com/655344/56853439-46444b80-6928-11e9-8129-44fe1b7ae55b.gif)

**Comment by mtehver** [comment]
This should be fixed now, the fix will be in SDK 4.2.0RC2.
