### ISSUE TITLE
[Question] what font formats are supported?

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-carto-libs#10]
Quick question do carto mobile sdk support woff or woff2 fonts? (i am looking at making my styles as small as possible).
Woff font (montserrat) are around 10 times smaller!

**Comment by mtehver** [comment]
@farfromrefug I checked the changelog of FreeType and it seems that WOFF2 is supported only starting from FreeType 2.10.2. SDK uses FreeType 2.6.3, so WOFF2 is not supported ATM.

I did a quick test with the fonts Voyager style uses, WOFF2 fonts are 422KB vs 590KB zipped TTF fonts. So a substantial gain. I will try to merge the latest FreeType into the SDK.

**Comment by mtehver** [comment]
WOFF2 support is now included in 4.4.0RC1. Thus closing the issue.
