### ISSUE TITLE
color parsing error breaks all tile

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-carto-libs#12]
I have a vector tile with a wrongly defined attribute which i use for color. So `white-red` is passed as a color.
The color parser correctly reports the issue with:
```
MBVectorTileDecoder::decodeTile: Exception while decoding: Could not parse to the end of color, error at position 5: white-red
```
The  thing is that it throws and then breaks the whole tile. So i end up with a missing tile (you can see the limit of the tile in the screenshot).
The feature itself should not be drawn, however it should not prevent the whole tile from being drawn, right?
<img width="365" alt="Screenshot 2021-07-15 at 16 09 45" src="https://user-images.githubusercontent.com/655344/125802206-61164002-2361-4e07-9982-17d6f64cb004.png">

**Comment by mtehver** [comment]
Right, this failure should not propagate to tile level, dropping related features should be enough. I will fix this.

**Comment by farfromrefug** [comment]
I think it is fixed now
