### ISSUE TITLE
placement-priority for lines/polygons

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-carto-libs#19]
I would like a way to make the "selected" item within a GeoJSON layer always appear on top of others.
I think `placement-priority` could do that. Could you add it for line/polygon?
BTW is there a value to "disable" placement-priority? is "none" supported like it is in carto css? That way i could do 
```
line-placement-priority: [nuti::selected_id]=[id] ? 1000 : none;
```

**Comment by mtehver** [comment]
It would be very hard to implement that. Processing of labels is very different from lines/polygons. Rendering of lines, polygons and basic points scales easily to hundreds of thousands features, while label processing really scales to few thousands.

**Comment by farfromrefug** [comment]
@mtehver so there is no way to say draw this polyline last?

**Comment by mtehver** [comment]
No way unfortunately. I suggest adding another layer for selected elements that is simply rendered on top of existing layers. So I would keep selection logic separate from base layer styling.

**Comment by farfromrefug** [comment]
@mtehver yes but i cant do it without  this https://github.com/CartoDB/mobile-carto-libs/issues/20 ;)

**Comment by farfromrefug** [comment]
solved with `when`
