### ISSUE TITLE
unwanted created rules

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-carto-libs#2]
Now that we have csstoxml it is easy to see and debug rules creation, and thus potential "heavy" and slow loading styles.
I attached a style showing some examples of unwanted rules.
[test.zip](https://github.com/CartoDB/mobile-carto-libs/files/3558715/test.zip)

If you run it as it is (using road2.mss), you will see in the generated rules a rule with a filter like this ```[class] = 'motorway' and [brunnel] = 'tunnel' and [subclass] = 'funicular'```
That rule is not wrong but unecessary and in a sense not wanted as not defined by the user. In my case of example i knew that rule would never happen, that's why i did not explicitly said that ```funicular``` was of class ```path```. All other rules are enough to define the style that i want. It is not a big deal render wise, but it is style wise because of those unwanted rules make the style heavier and slower to load.  With my full style, removing that issue by defining a class for funicular reduced the size of my style by around 30%.

Now if you change in the style JSON  'road2.mss' for 'road.mss' you will see something else.
In the resulting xml you will see that some rules are separated when they can be put together. For example ```[class] = 'motorway' and [zoom] &gt;= '4' or ( [class] = 'trunk' and [zoom] &gt;= '7' )``` and ```[class] = 'motorway' and [ramp] = '1' and [zoom] &gt;= '7' or ( [class] = 'trunk' and [ramp] = '1' and [zoom] &gt;= '13' )```.
Is there a maximum size for the Filter? If not merging those rules together would make a style smaller and faster to load.

**Comment by farfromrefug** [comment]
After a lot of testing i can confirm that using "sub" keys like ```service``` create a huge amount of unwanted rules.
By removing them (even though i need them) i went from 33Mo to 900kb ... ;)

**Comment by mtehver** [comment]
I briefly looked at the generated output and I do not see how the rules can be combined. Note that the rules are executed in order, thus even if the symbolizers are the same for 2 non-consecutive rules, there is at least one rule between them that can be potentially executed.

**Comment by farfromrefug** [comment]
@mtehver yes i understand the "in-beetween" rule which can exist. But i don't think it is necessary to create it in the xml. What i mean is that only specifically mentionned rules in the mss should be created in the XML.
I will try and send you an example with service for class=rail. It create a huge amount of rules.
