### ISSUE TITLE
color functions not working with variables or ternary operators

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-carto-libs#21]
If i do this :
```
line-color:desaturate([color], 30%);
```
it wont work
this neither
```
line-color:desaturate([color] ? [color] : @biking_route_fill, 30%);
```
while this work
```
line-color:desaturate(@biking_route_fill, 30%);
```

**Comment by mtehver** [comment]
@farfromrefug Correct, most color functions are evaluated at preprocessing stage and thus need constant arguments. This is how MapBox Studio Classic and original CartoCSS translation works. There are no Mapnik equivalents for `saturate`, `desaturate`, `darken` etc functions. So this is could be implemented, but I am giving this a low priority right now.

**Comment by farfromrefug** [comment]
@mtehver sure thing. Just feels weird cause you tend to want to try it in css ;)

**Comment by farfromrefug** [comment]
@mtehver i confirm the issue was with duplicate variable declaration
