### ISSUE TITLE
Seg fault when using css2xml with latest carto sdk features

### ISSUE THREAD

**Issue by safe-bug** [CartoDB/mobile-carto-libs#24]
Hello

I'm using "exp" function in css styles, when I want to convert it to XML using css2xml program it fails with segfault. It didn't happen in the previous version of css2xml (before Carto 4.4.3 release). What is the problem?

Thanks

**Comment by mtehver** [comment]
@safe-bug Can you share your style? We need more info to investigate this.

**Comment by safe-bug** [comment]
@mtehver It fails even with only this part of the style 

```
[highway='trunk'],[highway='trunk_link']{
  line-width: exp([view::zoom]);
}
```

The XML output for the previous version was this:

```
<LineSymbolizer stroke=“#000” stroke-linecap="round" stroke-linejoin="round" stroke-width="exp([view::zoom])" />
```

**Comment by mtehver** [comment]
Thanks for reporting this, should be fixed now.

**Comment by safe-bug** [comment]
@mtehver Thanks, it's fixed now.
