### ISSUE TITLE
parse style cant get optimized

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-carto-libs#7]
I am looking at ways to optimize a style.
I see in your code [this](https://github.com/CartoDB/mobile-carto-libs/blob/master/mapnikvt/src/mapnikvt/Style.cpp#L33) function which is suppose to do that.

However it cant really do it because most of the time rules are not "consecutive".

As an example in my generated xml. The same rule appears 13 times but as ou can see in the ruler they are not consecutive!
Maybe we could sort the rules first so that they are.

<img width="1079" alt="Screen Shot 2020-04-07 at 14 29 36" src="https://user-images.githubusercontent.com/655344/78669443-8e137700-78dc-11ea-81b4-8fc427fb92ae.png">

**Comment by farfromrefug** [comment]
I also see  `Filter::Type::ELSEFILTER` references in the code. It seems to be doable in XML. Is there a way to do that in mss? So that it will generate `ElseFilter` ? 
That could drastically decrease the size/complexity of my style!

**Comment by mtehver** [comment]
There is no way to express ELSE in CartoCSS. 

I recommend using CartoCSS styles directly (without precompiling into XML) with SDK 4.4. CartoCSS styles should now work faster when used directly vs XML styles.
