### ISSUE TITLE
Error while using css2xml tool

### ISSUE THREAD

**Issue by safe-bug** [CartoDB/mobile-carto-libs#9]
Hello
I've tried to use your prebuilt css2xml tool ([from here](https://drive.google.com/open?id=13giu6SHiknI45xAmjttWuLcNTd25GOq3)) to convert my css style to xml to find out if there's an issue with the style that makes it so slow when loading. But whatever style that I set as input, it fails with the below error:

`Exception while compiling: Error while parsing map description: syntax error at line 1 near: Map {` 

or 

`Exception while compiling: Error while parsing map description: syntax error at line 1 near: #admin {`

I've even tried the style file that is mentioned [here](https://github.com/CartoDB/mobile-carto-libs/issues/2). What is the problem? @mtehver @farfromrefug  Do you have any idea?

**Comment by mtehver** [comment]
My guess is that the style is not correctly packaged. Can you send your style asset and your style loading code? Or even better, make a small test project with assets that demonstrates the issue?

**Comment by safe-bug** [comment]
Thanks for your reply @mtehver, yes the problem was with my input file.
